### ISSUE TITLE
Install error because weak password

### ISSUE THREAD

**Issue by lexavey** [egandro/docker-qemu-arm#19]
Would be great if the script provide check for minimum password requirements, thankyou.

```
Changing password for root
New password:
Bad password: too weak
```

**Comment by leetree2001** [comment]
Don't know what happened, not, and will try to be insulting, YOU CAN FIX
THE SCRIPT. Or just don't run it, I make that decision all the time and
just blame Google..

**Comment by leetree2001** [comment]
Not saying that, but we ALL are

**Comment by egandro** [comment]
> Would be great if the script provide check for minimum password requirements, thankyou.
> 
> ```
> Changing password for root
> New password:
> Bad password: too weak
> ```

It's a user error. I just installed it with my default installer.

Check this line: https://github.com/egandro/docker-qemu-arm/blob/8f57e7739aadb12515992eed9bf51dcbe09131d6/config.sample#L11

You need to have "some" complexity in your Root password.

Please consider reading the Alpine Manual what that means. I didn't invent it. I don't care (since it's a user thing) and we can't fix it. Check this: we use expect to remote the alpine installer: https://github.com/egandro/docker-qemu-arm/blob/8f57e7739aadb12515992eed9bf51dcbe09131d6/installqemu.expect#L101

If you use a password that alpine does not like - the installation horrible crashes.... but that's the point :)

1) setup a proper password
2) use a manual installer.
